CREATE TABLE users (
    id SERIAL PRIMARY KEY,  
    email VARCHAR(255) UNIQUE,
    names VARCHAR(255),
    password VARCHAR(255),
    isVerified BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,  
    name VARCHAR(255),
    price DECIMAL(10, 2),
    count INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE carts (
    id SERIAL PRIMARY KEY,  
    user_id INT REFERENCES users(id) ON DELETE CASCADE,  
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
