CREATE TABLE users (
    id SERIAL PRIMARY KEY,  
    email VARCHAR(255) UNIQUE NOT NULL,
    names VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    isverified BOOLEAN DEFAULT FALSE,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,  
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL ,
    count INT NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE carts (
    id SERIAL PRIMARY KEY,  
    userid INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,  
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
    id SERIAL PRIMARY KEY,  
    cartid INT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,  
    productid INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,  
    quantity INT NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
